"""Regenerates figures/model_architecture.{png,svg}, the pipeline diagram of the
final model. Run from the repo root: .venv/bin/python figures/architecture.py
Numbers in the result strip are copied from results.md / main.ipynb section 14."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

C1, C2, C3, INK, MUTED, PAPER = "#2a78d6", "#eb6834", "#1baf7a", "#0b0b0b", "#52514e", "#ffffff"
fig, ax = plt.subplots(figsize=(15, 8), dpi=200)
ax.set_xlim(0, 135); ax.set_ylim(0, 76); ax.axis("off"); fig.patch.set_facecolor(PAPER)


def box(x, y, w, h, title, lines=(), ec=INK, lw=1.4, dashed=False, tc=INK, title_size=10, size=7.8, gap=3.3):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.4,rounding_size=1.2",
                                fc=PAPER, ec=ec, lw=lw, ls="--" if dashed else "-"))
    ax.text(x + w / 2, y + h - 3.0, title, ha="center", va="center", fontsize=title_size, weight="bold", color=tc)
    for i, ln in enumerate(lines):
        ax.text(x + w / 2, y + h - 6.6 - gap * i, ln, ha="center", va="center", fontsize=size, color=tc)


def arrow(x1, y1, x2, y2, color=INK, dashed=False, lw=1.4):
    ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle="-|>", mutation_scale=13, color=color, lw=lw,
                                 ls="--" if dashed else "-", shrinkA=2, shrinkB=2))


# ---- main pipeline band
Y, H = 37, 21
X = [(1, 25), (29, 26), (58, 26), (87, 27), (117, 17)]   # (x, width)
box(X[0][0], Y, X[0][1], H, "Inputs", ["train.csv: 141,772 tx, steps 1-35", "165 features, 78% unlabelled",
                            "test.csv: 15,329 tx, steps 36-49", "edge list: 234,355 edges"])
box(X[1][0], Y, X[1][1], H, "Feature cleaning", ["drop 6 period identifiers found by", "adversarial validation (AUC > 0.95)",
                                      "159 features remain", "31,235 labelled training rows"], ec=C1)
box(X[2][0], Y, X[2][1], H, "Per-step normalisation", ["9 drifting continuous features", "replaced by their percentile rank",
                                            "within their own time step;", "no statistics cross periods"], ec=C1)
box(X[3][0], Y, X[3][1], H, "LightGBM, 5-seed bag", ["300 rounds, lr 0.03, 31 leaves", "80% rows, 60% columns per tree",
                                          "no class weight: AUC is rank-based", "average of 5 probabilities"], ec=C2, lw=2)
box(X[4][0], Y, X[4][1], H, "Output", ["P(illicit)", "per transaction", "", "submission.csv"], ec=C3)
for (xa, wa), (xb, _) in zip(X[:-1], X[1:]):
    arrow(xa + wa, Y + H / 2, xb, Y + H / 2)

# ---- validation band (top)
box(29, 65, 85, 10.5, "Validation: rolling-origin folds by time_step, labelled rows only",
    ["train 1-14 > val 15-21   |   train 1-21 > val 22-28   |   train 1-28 > val 29-35",
     "horizon fold: train 1-21 > val 22-35, 14 steps ahead like the test set"],
    ec=MUTED, tc=MUTED, title_size=9.5, size=8, gap=3.1)
arrow(42, 65, 42, Y + H, color=MUTED)
ax.text(43.5, 61.8, "adversarial validation decides\nwhich columns to drop or rank", fontsize=7.6, color=MUTED, ha="left", va="center")
arrow(100, 65, 100, Y + H, color=MUTED)
ax.text(101.5, 61.8, "rolling CV picks rounds,\nfeature variant and seed bag", fontsize=7.6, color=MUTED, ha="left", va="center")

# ---- rejected band (bottom)
ax.text(134, 33.6, "Tested on the same folds\nand rejected (dashed):", fontsize=9.2, weight="bold", color=MUTED, va="center", ha="right")
RB, RH = 15, 16
kw = dict(ec=MUTED, tc=MUTED, dashed=True, title_size=9.5, size=7.8, gap=3.2)
box(X[0][0], RB, X[0][1], RH, "Graph features", ["degree, coverage, DAG depth,", "PageRank, neighbour aggregates;", "rewired edges score the same"], **kw)
box(X[1][0], RB, X[1][1], RH, "Recency weighting", ["half-life 5 / 10 / 20 steps,", "window start 5 / 8 / 12: every", "setting lowers the horizon fold"], **kw)
box(X[2][0], RB, X[2][1], RH, "Score-level correction", ["within-step rank, EM prior, BBSE:", "all hurt; the oracle prior shows", "a +0.019 ceiling at most"], **kw)
box(X[3][0], RB, X[3][1], RH, "Blends", ["random forest 0.2 / 0.3 and", "isolation forest 0.1 - 0.3:", "all below LightGBM alone"], **kw)
for x, w in X[:-1]:
    arrow(x + w / 2, RB + RH, x + w / 2, Y, color=MUTED, dashed=True)

# ---- result strip
ax.text(1, 10.5, "Rolling CV of the final model, mean of 3 seeds:   7-step folds 0.9822   |   hard fold 22-28: 0.9567   |   "
                 "14-step horizon fold: 0.9135   |   public leaderboard 0.942", fontsize=9, color=INK, va="center")
ax.text(1, 6.8, "Solid path = final model (sub_04). Blue = feature steps, orange = learner, green = output, "
                "grey = protocol and rejected branches.", fontsize=8.2, color=MUTED, va="center")
ax.text(1, 3.4, "BT4012, fraudulent cryptocurrency transactions. Generated by figures/architecture.py "
                "from the results in main.ipynb.", fontsize=7.5, color=MUTED, va="center")

plt.savefig("figures/model_architecture.png", bbox_inches="tight", facecolor=PAPER)
plt.savefig("figures/model_architecture.svg", bbox_inches="tight", facecolor=PAPER)
print("saved figures/model_architecture.png and .svg")
